repos:
  - repo: local
    hooks:
      - id: format-and-stage
        name: Format and auto-stage
        entry: bash -c 'make format && git add -u'
        language: system
        pass_filenames: false
        always_run: true